name: Automatic Sign In
on:
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: 
     - name: fish sign
       env:
        COOKIE: ${secrets.FISHC_COOKIE
       run: |
          python fishcsign.py $COOKIE

